language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install mock; fi
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -e .
  - pip install codecov

script:
  - python runtests.py
  - coverage run --source='iitgauth' runtests.py

after_success:
- bash <(curl -s https://codecov.io/bash)
